package com.innovative.airportweather;
public enum Airport {
	ABR ("Aberdeen, SD", "ABR"),  
	ABI ("Abilene, TX", "ABI"), 
	ADK ("Adak Island, AK", "ADK"), 
	KKI ("Akiachak, AK", "KKI"), 
	AKI ("Akiak, AK" , "AKI"), 
	CAK ("Akron/Canton, OH",  "CAK"), 
	KQA ("Akuton, AK",  "KQA"), 
	AUK ("Alakanuk, AK",  "AUK"), 
	ALM ("Alamogordo, NM",  "ALM"), 
	ALS ("Alamosa, CO",  "ALS"), 
	ALB ("Albany, NY",  "ALB"), 
	CVO ("Albany, OR - Bus service",  "CVO"), 
	ABQ ("Albuquerque, NM",  "ABQ"), 
	WWK ("Aleknagik, AK",  "WKK"), 
	AEX ("Alexandria, LA",  "AEX"), 
	AET ("Allakaket, AK",  "AET"), 
	ABE ("Allentown/Bethlehem/Easton, PA",  "ABE"), 
	AIA ("Alliance, NE",  "AIA"), 
	APN ("Alpena, MI",  "APN"), 
	AOO ("Altoona/Martinsburg, PA",  "AOO"), 
	AMA ("Amarillo, TX",  "AMA"), 
	ABL ("Ambler, AK",  "ABL"), 
	AKP ("Anaktueuk, AK",  "AKP"), 
	ANC ("Anchorage, AK",  "ANC"), 
	AGN ("Angoon, AK",  "AGN"), 
	ANI ("Aniak, AK",  "ANI"), 
	ANV ("Anvik, AK",  "ANV"), 
	ATW ("Appleton, WI",  "ATW"), 
	ACV ("Arcata/Eureka/Arcata, CA",  "ACV"),
	ARC ("Arctic Village, AK",  "ARC"), 
	AVL ("Asheville/Hendersonville, NC",  "AVL"),
	HTS ("Ashland, KY/Huntington, WV",  "HTS"),
	ASE ("Aspen, CO",  "ASE"), 
	AHN ("Athens, GA",  "AHN"), 
	AKB ("Atka, AK",  "AKB"), 
	ATL ("Atlanta, GA",  "ATL"), 
	AIY ("Atlantic City, NJ",  "AIY"), 
	ATK ("Atqasuk, AK",  "ATK"), 
	AGS ("Augusta, GA",  "AGS"), 
	AUG ("Augusta, ME",  "AUG"), 
	AUS ("Austin, TX",  "AUS"), 
	
	BFL ("Bakersfield, CA",  "BFL"),
	BWI ("Baltimore, MD",  "BWI"),
	BGR ("Bangor, ME",  "BGR"),
	BHB ("Bar Harbour, ME",  "BHB"),
	BRW ("Barrow, AK",  "BRW"),
	BTI ("Barter Island, AK",  "BTI"),
	BTR ("Baton Rouge, LA",  "BTR"),
	MBS ("Bay City/Midland, MI",  "MBS"),
	BPT ("Beaumont/Port Arthur, TX",  "BPT"),
	ZBV ("Beaver Creek, CO - Van service",  "ZBV"),
	WBQ ("Beaver, AK",  "WBQ"),
	BKW ("Beckley, WV",  "BKW"),
	BED ("Bedford, MA",  "BED"),
	BLV ("Belleville, IL",  "BLV"),
	BLI ("Bellingham, WA",  "BLI"),
	BJI ("Bemidji, MN",  "BJI"),
	BEH ("Benton Harbor, MI",  "BEH"),
	BET ("Bethel, AK",  "BET"),
	
	BTT ("Bettles, AK",  "BTT"),
	BIL ("Billings, MT",  "BIL"),
	GPT ("Biloxi/Gulfport, MS",  "GPT"),
	BGM ("Binghamton/Johnson City, NY",  "BGM"),
	KBC ("Birch Creek, AK",  "KBC"),
	BHM ("Birmingham, AL",  "BHM"),
	BIS ("Bismarck, ND",  "BIS"),
	BID ("Block Island, RI",  "BID"),
	BMI ("Bloomington, IL",  "BMI"),
	BLF ("Bluefield, WV",  "BLF"),
	BOI ("Boise, ID",  "BOI"),
	BOS ("Boston, MA",  "BOS"),
	XHH ("Boulder, CO - Bus service",  "XHH"),
	WHH ("Boulder, CO - Hiltons Har H",  "WHH"),
	WBU ("Boulder, CO - Municipal Airport",  "WBU"),
	BYA ("Boundary, AK",  "BYA"),
	BWG ("Bowling Green, KY",  "BWG"),
	BZN ("Bozeman, MT",  "BZN"),
	BFD ("Bradford, PA",  "BFD"),
	BRD ("Brainerd, MN",  "BRD"),
	BWD ("Brawnwood, TX",  "BWD"),
	QKB ("Breckonridge, CO - Van service",  "QKB"),
	TRI ("Bristol, VA / Johnson City/Kingsport, TN",  "TRI"),
	BKX ("Brookings, SD",  "BKX"),
	RBH ("Brooks Lodge, AK",  "RBH"),
	BRO ("Brownsville, TX",  "BRO"),
	BQK ("Brunswick, GA",  "BQK"),
	BKC ("Buckland, AK",  "BKC"),
	BUF ("Buffalo, NY",  "BUF"),
	IFP ("Bullhead City/Laughlin, AZ",  "IFP"),
	BUR ("Burbank, CA",  "BUR"),
	BRL ("Burlington, IA",  "BRL"),
	BTV ("Burlington, VT",  "BTV"),
	BTM ("Butte, MT",  "BTM"),

	CGI ("Cape Girardeau, MO",  "CGI"),
	LUR ("Cape Lisburne, AK",  "LUR"),
	EHM ("Cape Newenham, AK",  "EHM"),
	MDH ("Carbondale, IL",  "MDH"),
	CLD ("Carlsbad, CA",  "CLD"),
	CNM ("Carlsbad, NM",  "CNM"),
	
	CPR ("Casper, WY",  "CPR"),
	CDC ("Cedar City, UT",  "CDC"),
	CID ("Cedar Rapids, IA",  "CID"),
	CEM ("Central, AK",  "CEM"),
	CDR ("Chadron, NE",  "CDR"),
	CIK ("Chalkyitsik, AK",  "CIK"),
	CMI ("Champaign/Urbana, IL",  "CMI"),
	CHS ("Charleston, SC",  "CHS"),
	CRW ("Charleston, WV",  "CRW"),
	CLT ("Charlotte, NC",  "CLT"),
	CHO ("Charlottesville, VA",  "CHO"),
	CHA ("Chattanooga, TN",  "CHA"),
	CYF ("Chefornak, AK",  "CYF"),
	VAK ("Chevak, AK",  "VAK"),
	CYS ("Cheyenne, WY",  "CYS"),
	CGX ("Chicago, IL - Meigs",  "CGX"),
	CHI ("Chicago, IL - All airports",  "CHI"),
	MDW ("Chicago, IL - Midway",  "MDW"),
	ORD ("Chicago, IL - O'Hare",  "ORD"),
	CKX ("Chicken, AK",  "CKX"),
	CIC ("Chico, CA",  "CIC"),
	KCG ("Chignik, AK - Fisheries",  "KCG"),
	KCQ ("Chignik, AK -",  "KCQ"),
	KCL ("Chignik, AK - Lagoon",  "KCL"),
	CZN ("Chisana, AK",  "CZN"),
	CHU ("Chuathbaluk, AK",  "CHU"),
	CVG ("Cincinnati, OH",  "CVG"),
	CHP ("Circle Hot Springs, AK",  "CHP"),
	IRC ("Circle, AK",  "IRC"),
	CLP ("Clarks Point, AK",  "CLP"),
	CKB ("Clarksburg, WV",  "CKB"),
	PIE ("Clearwater/St Petersburg, FL",  "PIE"),
	CLE ("Cleveland, OH",  "CLE"),
	CVN ("Clovis, NM",  "CVN"),
	COD ("Cody/Yellowstone, WY",  "COD"),
	CFA ("Coffee Point, AK",  "CFA"),
	KCC ("Coffman Cove, AK",  "KCC"),
	CDB ("Cold Bay, AK",  "CDB"),
	CLL ("College Station, TX",  "CLL"),
	COS ("Colorado Springs, CO",  "COS"),
	COU ("Columbia, MO",  "COU"),
	CAE ("Columbia, SC",  "CAE"),
	CSG ("Columbus, GA",  "CSG"),
	GTR ("Columbus, MS",  "GTR"),
	CMH ("Columbus, OH",  "CMH"),
	CCR ("Concord, CA",  "CCR"),
	CNK ("Concordia, KS",  "CNK"),
	QCE ("Copper Mountain, CO - Van service",  "QCE"),
	CDV ("Cordova, AK",  "CDV"),
	CRP ("Corpus Christi, TX",  "CRP"),
	CEZ ("Cortez, CO",  "CEZ"),
	CGA ("Craig, AK",  "CGA"),
	CEC ("Crescent City, CA",  "CEC"),
	CKO ("Crooked Creek, AK",  "CKO"),
	CUW ("Cube Cove, AK",  "CUW"),
	CBE ("Cumberland, MD",  "CBE"),


	
	DAY ("Dayton, OH",  "DAY"),
	DAB ("Daytona Beach, FL",  "DAB"),
	DEC ("Decatur, IL",  "DEC"),
	DRG ("Deering, AK",  "DRG"),
	DJN ("Delta Junction, AK",  "DJN"),
	DEN ("Denver, CO - International",  "DEN"),
	QWM ("Denver, CO - Longmont Bus service",  "QWM"),
	DSM ("Des Moines, IA",  "DSM"),
	DTT ("Detroit, MI - All airports",  "DTT"),
	DTW ("Detroit, MI - Metro/Wayne County",  "DTW"),
	DVL ("Devil's Lake, ND",  "DVL"),
	DIK ("Dickinson, ND",  "DIK"),
	DLG ("Dillingham, AK",  "DLG"),
	DDC ("Dodge City, KS",  "DDC"),
	DHN ("Dothan, AL",  "DHN"),
	DUJ ("Dubois, PA",  "DUJ"),
	DBQ ("Dubuque, IA",  "DBQ"),
	DLH ("Duluth, MN",  "DLH"),
	DRO ("Durango, CO",  "DRO"),
	RDU ("Durham/Raleigh, NC",  "RDU"),
	DUT ("Dutch Harbor, AK",  "DUT"),


	EAU ("Eau Claire, WI",  "EAU"),
	EDA ("Edna Bay, AK",  "EDA"),
	EEK ("Eek, AK",  "EEK"),
	KKU ("Ekuk, AK",  "KKU"),
	KEK ("Ekwok, AK",  "KEK"),
	IPL ("El Centro/Imperial, CA",  "IPL"),
	ELD ("El Dorado, AR",  "ELD"),
	ELP ("El Paso, TX",  "ELP"),
	ELV ("Elfin Cove, AK",  "ELV"),
	ELI ("Elim, AK",  "ELI"),
	EKO ("Elko, NV",  "EKO"),
	ELM ("Elmira, NY",  "ELM"),
	LYU ("Ely, MN",  "LYU"),
	EMK ("Emmonak, AK",  "EMK"),
	WDG ("Enid, OK",  "WDG"),
	ERI ("Erie, PA",  "ERI"),
	ESC ("Escanaba, MI",  "ESC"),
	EUG ("Eugene, OR",  "EUG"),
	
	EUE ("Eureka, NV",  "EUE"),
	EVV ("Evansville, IN",  "EVV"),


	FAI ("Fairbanks, AK",  "FAI"),
	FAR ("Fargo, ND",  "FAR"),
	FYV ("Fayetteville, AR - Municipal/Drake",  "FYV"),
	XNA ("Fayetteville, AR - Northwest Arkansas Regional",  "XNA"),
	FAY ("Fayetteville, NC",  "FAY"),
	FLG ("Flagstaff, AZ",  "FLG"),
	FNT ("Flint, MI",  "FNT"),
	FLO ("Florence, SC",  "FLO"),
	MSL ("Florence/Muscle Shoals/Sheffield/Muscle Shoals, AL",  "MSL"),
	FNL ("Fort Collins/Loveland, CO - Municipal Airport",  "FNL"),
	QWF ("Fort Collins/Loveland, CO - Bus service",  "QWF"),
	FOD ("Fort Dodge, IA",  "FOD"),
	FLL ("Fort Lauderdale, FL",  "FLL"),
	TBN ("Fort Leonard Wood, MO",  "TBN"),
	RSW ("Fort Myers, FL",  "RSW"),
	FSM ("Fort Smith, AR",  "FSM"),
	VPS ("Fort Walton Beach, FL",  "VPS"),
	FWA ("Fort Wayne, IN",  "FWA"),
	DFW ("Dallas/Fort/Worth, TX",  "DFW"),
	FKL ("Franklin, PA",  "FKL"),
	FAT ("Fresno, CA",  "FAT"),


	GNV ("Gainesville, FL",  "GNV"),
	GUP ("Gallup, NM",  "GUP"),
	GCK ("Garden City, KS",  "GCK"),
	GYY ("Gary, IN",  "GYY"),
	GCC ("Gillette, WY",  "GCC"),
	GGG ("Gladewater/Kilgore/Longview, TX",  "GGG"),
	GGW ("Glasgow, MT",  "GGW"),
	GDV ("Glendive, MT",  "GDV"),
	GLV ("Golovin, AK",  "GLV"),
	GNU ("Goodnews Bay, AK",  "GNU"),
	JGC ("Grand Canyon, AZ - Heliport",  "JGC"),
	GCN ("Grand Canyon, AZ - National Park",  "GCN"),
	GFK ("Grand Forks, ND",  "GFK"),
	GRI ("Grand Island, NE",  "GRI"),
	GJT ("Grand Junction, CO",  "GJT"),
	GRR ("Grand Rapids, MI",  "GRR"),
	GPZ ("Grand Rapids, MN",  "GPZ"),
	KGX ("Grayling, AK",  "KGX"),
	GTF ("Great Falls, MT",  "GTF"),
	GRB ("Green Bay, WI",  "GRB"),
	
	GLH ("Greenville, MS",  "GLH"),
	PGV ("Greenville, NC",  "PGV"),
	GSP ("Greenville/Spartanburg, SC",  "GSP"),
	GON ("Groton/New London, CT",  "GON"),
	
	GUC ("Gunnison, CO",  "GUC"),
	GST ("Gustavus, AK",  "GST"),


	HGR ("Hagerstown, MD",  "HGR"),
	SUN ("Hailey, ID",  "SUN"),
	HNS ("Haines, AK",  "HNS"),
	PHF ("Hampton/Newport News, VA",  "PHF"),
	HNM ("Hana, HI - Island of Maui",  "HNM"),
	PAK ("Hanapepe, HI",  "PAK"),
	CMX ("Hancock, MI",  "CMX"),
	LEB ("Hanover/Lebanon, NH",  "LEB"),
	HRL ("Harlingen, TX",  "HRL"),
	MDT ("Harrisburg, PA",  "MDT"),
	HRO ("Harrison, AR",  "HRO"),
	BDL ("Hartford, CT",  "BDL"),
	HAE ("Havasupai, AZ",  "HAE"),
	HVR ("Havre, MT",  "HVR"),
	HDN ("Hayden, CO",  "HDN"),
	HYS ("Hays, KS",  "HYS"),
	HKB ("Healy Lake, AK",  "HKB"),
	HLN ("Helena, MT",  "HLN"),
	
	HIB ("Hibbing/Chisholm, MN",  "HIB"),
	HYK ("Hickory, NC",  "HKY"),
	GSO ("High Point/Greensboro, NC",  "GSO"),
	ITO ("Hilo, HI - Island of Hawaii",  "ITO"),
	HHH ("Hilton Head, SC",  "HHH"),
	HBB ("Hobbs, NM",  "HBB"),
	HYL ("Hollis, AK",  "HYL"),
	HCR ("Holy Cross, AK",  "HCR"),
	HOM ("Homer, AK",  "HOM"),
	HNL ("Honolulu, HI - Island of Oahu",  "HNL"),
	MKK ("Hoolehua, HI - Island of Molokai",  "MKK"),
	HNH ("Hoonah, AK",  "HNH"),
	HPB ("Hooper Bay, AK",  "HPB"),
	HOT ("Hot Springs, AR",  "HOT"),
	HOU ("Houston, TX - All airports",  "HOU"),
	IAH ("Houston, TX - Intercontinental",  "IAH"),
	HUS ("Hughes, AK",  "HUS"),
	
	HSV ("Huntsville, AL",  "HSV"),
	HON ("Huron, SD",  "HON"),
	HSL ("Huslia, AK",  "HSL"),
	HYA ("Hyannis, MA",  "HYA"),
	HYG ("Hydaburg, AK",  "HYG"),


	IDA ("Idaho Falls, ID",  "IDA"),
	IGG ("Igiugig, AK",  "IGG"),
	ILI ("Iliamna, AK",  "ILI"),
	
	IND ("Indianapolis, IN",  "IND"),
	INL ("International Falls, MN",  "INL"),
	IYK ("Inyokern, CA",  "IYK"),
	IMT ("Iron Mountain, MI",  "IMT"),
	IWD ("Ironwood, MI",  "IWD"),
	ISP ("Islip, NY",  "ISP"),
	ITH ("Ithaca, NY",  "ITH"),


	JAC ("Jackson Hole, WY",  "JAC"),
	JAN ("Jackson, MS",  "JAN"),
	MKL ("Jackson, TN",  "MKL"),
	JAX ("Jacksonville, FL",  "JAX"),
	OAJ ("Jacksonville, NC",  "OAJ"),
	JMS ("Jamestown, ND",  "JMS"),
	JHW ("Jamestown, NY",  "JHW"),
	JVL ("Janesville, WI",  "JVL"),
	
	
	JST ("Johnstown, PA",  "JST"),
	JBR ("Jonesboro, AR",  "JBR"),
	JLN ("Joplin, MO",  "JLN"),
	JNU ("Juneau, AK",  "JNU"),


	OGG ("Kahului/Maui, HI - Island of Maui,",  "OGG"),
	KAE ("Kake, AK",  "KAE"),
	KNK ("Kakhonak, AK",  "KNK"),
	AZO ("Kalamazoo, MI",  "AZO"),
	LUP ("Kalaupapa, HI - Island of Molokai,",  "LUP"),
	KLG ("Kalskag, AK",  "KLG"),
	KAL ("Kaltag, AK",  "KAL"),
	MUE ("Kamuela, HI - Island of Hawaii,",  "MUE"),
	MCI ("Kansas City, MO",  "MCI"),
	JHM ("Kapalua, HI - Island of Maui,",  "JHM"),
	KXA ("Kasaan, AK",  "KXA"),
	KUK ("Kasigluk, AK",  "KUK"),
	LIH ("Kauai Island/Lihue, HI",  "LIH"),
	EAR ("Kearney, NE",  "EAR"),
	EEN ("Keene, NH",  "EEN"),
	ENA ("Kenai, AK",  "ENA"),
	KTN ("Ketchikan, AK",  "KTN"),
	EYW ("Key West, FL",  "EYW"),
	QKS ("Keystone, CO - Van service",  "QKS"),
	IAN ("Kiana, AK",  "IAN"),
	
	ILE ("Killeen, TX",  "ILE"),
	KVC ("King Cove, AK",  "KVC"),
	AKN ("King Salmon, AK",  "AKN"),
	IGM ("Kingman, AZ",  "IGM"),
	
	KPN ("Kipnuk, AK",  "KPN"),
	IRK ("Kirksville, MO",  "IRK"),
	KVL ("Kivalina, AK",  "KVL"),
	LMT ("Klamath Falls, OR",  "LMT"),
	KLW ("Klawock, AK",  "KLW"),
	TYS ("Knoxville, TN",  "TYS"),
	OBU ("Kobuk, AK",  "OBU"),
	ADQ ("Kodiak, AK",  "ADQ"),
	KOA ("Kona, HI - Island of Hawaii",  "KOA"),
	KKH ("Kongiganak, AK",  "KKH"),
	KOT ("Kotlik, AK",  "KOT"),
	OTZ ("Kotzebue, AK",  "OTZ"),
	KYU ("Koyukuk, AK",  "KYU"),
	KWT ("Kwethluk, AK",  "KWT"),
	KWK ("Kwigillingok, AK",  "KWK"),


	LSE ("La Crosse, WI",  "LSE"),
	LAF ("Lafayette, IN",  "LAF"),
	LFT ("Lafayette, LA",  "LFT"),
	LCH ("Lake Charles, LA",  "LCH"),
	HII ("Lake Havasu City, AZ",  "HII"),
	LMA ("Lake Minchumina, AK",  "LMA"),
	LNY ("Lanai City, HI - Island of Lanai",  "LNY"),
	LNS ("Lancaster, PA",  "LNS"),
	LAN ("Lansing, MI",  "LAN"),
	LAR ("Laramie, WY",  "LAR"),
	LRD ("Laredo, TX",  "LRD"),
	LAS ("Las Vegas, NV",  "LAS"),
	LBE ("Latrobe, PA",  "LBE"),
	PIB ("Laurel, MS",  "PIB"),
	LAW ("Lawton, OK",  "LAW"),
	
	KLL ("Levelock, AK",  "KLL"),
	LWB ("Lewisburg, WV",  "LWB"),
	LWS ("Lewiston, ID",  "LWS"),
	LWT ("Lewistown, MT",  "LWT"),
	LEX ("Lexington, KY",  "LEX"),
	LBL ("Liberal, KS",  "LBL"),
	
	LNK ("Lincoln, NE",  "LNK"),
	LIT ("Little Rock, AR",  "LIT"),
	LGB ("Long Beach, CA",  "LGB"),
	
	LPS ("Lopez Island, WA",  "LPS"),
	LAX ("Los Angeles, CA",  "LAX"),
	SDF ("Louisville, KY",  "SDF"),
	 
	
	LBB ("Lubbock, TX",  "LBB"),


	MCN ("Macon, GA",  "MCN"),
	MSN ("Madison, WI",  "MSN"),
	MDJ ("Madras, OR",  "MDJ"),
	MHT ("Manchester, NH",  "MHT"),
	MHK ("Manhattan, KS",  "MHK"),
	MBL ("Manistee, MI",  "MBL"),
	MKT ("Mankato, MN",  "MKT"),
	MLY ("Manley Hot Springs, AK",  "MLY"),
	KMO ("Manokotak, AK",  "KMO"),
	PKB ("Marietta, OH/Parkersburg, WV",  "PKB"),
	MWA ("Marion, IL",  "MWA"),
	MQT ("Marquette, MI",  "MQT"),
	MLL ("Marshall, AK",  "MLL"),
	MVY ("Martha's Vineyard, MA",  "MVY"),
	MCW ("Mason City, IA",  "MCW"),
	MSS ("Massena, NY",  "MSS"),
	
	
	MCK ("Mccook, NE",  "MCK"),
	MCG ("Mcgrath, AK",  "MCG"),
	MFR ("Medford, OR",  "MFR"),
	MYU ("Mekoryuk, AK",  "MYU"),
	MLB ("Melbourne, FL",  "MLB"),
	MEM ("Memphis, TN",  "MEM"),
	MCE ("Merced, CA",  "MCE"),
	MEI ("Meridian, MS",  "MEI"),
	MTM ("Metlakatla, AK",  "MTM"),
	WMK ("Meyers Chuck, AK",  "WMK"),
	MIA ("Miami, FL - International",  "MIA"),
	MPB ("Miami, FL - Sea Plane Base",  "MPB"),
	
	MAF ("Midland/Odessa, TX",  "MAF"),
	MLS ("Miles City, MT",  "MLS"),
	MKE ("Milwaukee, WI",  "MKE"),
	MSP ("Minneapolis, MN",  "MSP"),
	MOT ("Minot, ND",  "MOT"),
	MNT ("Minto, AK",  "MNT"),
	MFE ("Mission/Mcallen, TX",  "MFE"),
	MSO ("Missoula, MT",  "MSO"),
	CNY ("Moab, UT",  "CNY"),
	MOB ("Mobile, AL",  "MOB"),
	MOD ("Modesto, CA",  "MOD"),
	MLI ("Moline, IL",  "MLI"),
	MLU ("Monroe, LA",  "MLU"),
	MRY ("Monterey/Carmel, CA",  "MRY"),
	MGM ("Montgomery, AL",  "MGM"),
	MTJ ("Montrose, CO",  "MTJ"),
	MGW ("Morgantown, WV",  "MGW"),
	MWH ("Moses Lake, WA",  "MWH"),
	WMH ("Mountain Home, AR",  "WMH"),
	MOU ("Mountain Village, AK",  "MOU"),
	
	MKG ("Muskegon, MI",  "MKG"),
	MYR ("Myrtle Beach, SC",  "MYR"),


	ACK ("Nantucket, MA",  "ACK"),
	WNA ("Napakiak, AK",  "WNA"),
	PKA ("Napaskiak, AK",  "PKA"),
	APF ("Naples, FL",  "APF"),
	BNA ("Nashville, TN",  "BNA"),
	NKI ("Naukiti, AK",  "NKI"),
	NLG ("Nelson Lagoon, AK",  "NLG"),
	NCN ("New Chenega, AK",  "NCN"),
	HVN ("New Haven, CT",  "HVN"),
	KGK ("New Koliganek, AK",  "KGK"),
	
	MSY ("New Orleans, LA",  "MSY"),
	KNW ("New Stuyahok, AK",  "KNW"),
	NYC ("New York, NY - All airports",  "NYC"),
	JFK ("New York, NY - Kennedy",  "JFK"),
	LGA ("New York, NY - La Guardia",  "LGA"),
	EWR ("Newark, NJ",  "EWR"),
	SWF ("Newburgh/Stewart Field, NY",  "SWF"),
	
	WWT ("Newtok, AK",  "WWT"),
	NME ("Nightmute, AK",  "NME"),
	NIB ("Nikolai, AK",  "NIB"),
	IKO ("Nikolski, AK",  "IKO"),
	WTK ("Noatak, AK",  "WTK"),
	OME ("Nome, AK",  "OME"),
	NNL ("Nondalton, AK",  "NNL"),
	ORV ("Noorvik, AK",  "ORV"),
	OFK ("Norfolk, NE",  "OFK"),
	ORF ("Norfolk, VA",  "ORF"),
	OTH ("North Bend, OR",  "OTH"),
	LBF ("North Platte, NE",  "LBF"),
	ORT ("Northway, AK",  "ORT"),
	NUI ("Nuiqsut, AK",  "NUI"),
	NUL ("Nulato, AK",  "NUL"),
	NUP ("Nunapitchuk, AK",  "NUP"),


//	XXX ("Oakland, CA",  "OAK"),
//	XXX ("Odessa/Midland, TX",  "MAF"),
//	XXX ("Ogdensburg, NY",  "OGS"),
//	XXX ("Oklahoma City, OK",  "OKC"),
//	XXX ("Omaha, NE",  "OMA"),
//	XXX ("Ontario, CA",  "ONT"),
//	XXX ("Orange County, CA",  "SNA"),
//	XXX ("Orlando, FL - Herndon",  "ORL"),
//	XXX ("Orlando, FL - International",  "MCO"),
//	XXX ("Oshkosh, WI",  "OSH"),
//	XXX ("Ottumwa, IA",  "OTM"),
//	XXX ("Owensboro, KY",  "OWB"),
//	XXX ("Oxnard/Ventura, CA",  "OXR"),
//
//
//	XXX ("Paducah, KY",  "PAH"),
//	XXX ("Page, AZ",  "PGA"),
//	XXX ("Palm Springs, CA",  "PSP"),
//	XXX ("Panama City, FL",  "PFN"),
//	XXX ("Parkersburg, WV/Marietta, OH",  "PKB"),
//	XXX ("Pasco, WA",  "PSC"),
//	XXX ("Pedro Bay, AK",  "PDB"),
//	XXX ("Pelican, AK",  "PEC"),
//	XXX ("Pellston, MI",  "PLN"),
//	XXX ("Pendleton, OR",  "PDT"),
//	XXX ("Pensacola, FL",  "PNS"),
//	XXX ("Peoria, IL",  "PIA"),
//	XXX ("Perryville, AK",  "KPV"),
//	XXX ("Petersburg, AK",  "PSG"),
//	XXX ("Philadelphia, PA - International",  "PHL"),
//	XXX ("Philadelphia, PA - Trenton/Mercer NJ",  "TTN"),
//	XXX ("Phoenix, AZ",  "PHX"),
//	XXX ("Pierre, SD",  "PIR"),
//	XXX ("Pilot Point, AK - Ugashnik Bay",  "UGB"),
//	XXX ("Pilot Point, AK",  "PIP"),
//	XXX ("Pilot Station, AK",  "PQS"),
//	XXX ("Pittsburgh, PA",  "PIT"),
//	XXX ("Platinum, AK",  "PTU"),
//	XXX ("Plattsburgh, NY",  "PLB"),
//	XXX ("Pocatello, ID",  "PIH"),
//	XXX ("Point Baker, AK",  "KPB"),
//	XXX ("Point Hope, AK",  "PHO"),
//	XXX ("Point Lay, AK",  "PIZ"),
//	XXX ("Ponca City, OK",  "PNC"),
//	XXX ("Ponce, Puerto Rico",  "PSE"),
//	XXX ("Port Alsworth, AK",  "PTA"),
//	XXX ("Port Angeles, WA",  "CLM"),
//	XXX ("Port Arthur/Beaumont, TX",  "BPT"),
//	XXX ("Port Clarence, AK",  "KPC"),
//	XXX ("Port Heiden, AK",  "PTH"),
//	XXX ("Port Moller, AK",  "PML"),
//	XXX ("Port Protection, AK",  "PPV"),
//	XXX ("Portage Creek, AK",  "PCA"),
//	XXX ("Portland, ME",  "PWM"),
//	XXX ("Portland, OR",  "PDX"),
//	XXX ("Portsmouth, NH",  "PSM"),
//	XXX ("Poughkeepsie, NY",  "POU"),
//	XXX ("Prescott, AZ",  "PRC"),
//	XXX ("Presque Isle, ME",  "PQI"),
//	XXX ("Princeton, WV",  "BLF"),
//	XXX ("Providence, RI",  "PVD"),
//	XXX ("Provincetown, MA",  "PVC"),
//	XXX ("Prudhoe Bay/Deadhorse, AK",  "SCC"),
//	XXX ("Pueblo, CO",  "PUB"),
//	XXX ("Pullman, WA",  "PUW"),
//
//
//	XXX ("Quincy, IL",  "UIN"),
//	XXX ("Quinhagak, AK",  "KWN"),
//
//
//	XXX ("Raleigh/Durham, NC",  "RDU"),
//	XXX ("Rampart, AK",  "RMP"),
//	XXX ("Rapid City, SD",  "RAP"),
//	XXX ("Reading, PA",  "RDG"),
//	XXX ("Red Devil, AK",  "RDV"),
//	XXX ("Redding, CA",  "RDD"),
//	XXX ("Redmond, OR",  "RDM"),
//	XXX ("Reno, NV",  "RNO"),
//	XXX ("Rhinelander, WI,",  "RHI"),
//	XXX ("Richmond, VA",  "RIC"),
//	XXX ("Riverton, WY",  "RIW"),
//	XXX ("Roanoke, VA",  "ROA"),
//	XXX ("Roche Harbor, WA",  "RCE"),
//	XXX ("Rochester, MN",  "RST"),
//	XXX ("Rochester, NY",  "ROC"),
//	XXX ("Rock Springs, WY",  "RKS"),
//	XXX ("Rockford, IL - Park&Ride Bus",  "ZRF"),
//	XXX ("Rockford, IL - Van Galder Bus",  "ZRK"),
//	XXX ("Rockland, ME",  "RKD"),
//	XXX ("Rosario, WA",  "RSJ"),
//	XXX ("Roswell, NM",  "ROW"),
//	XXX ("Ruby, AK",  "RBY"),
//	XXX ("Russian Mission, AK",  "RSH"),
//	XXX ("Rutland, VT",  "RUT"),
//
//
//	XXX ("Sacramento, CA",  "SMF"),
//	XXX ("Saginaw, MI",  "MBS"),
//	XXX ("Saint Cloud, MN",  "STC"),
//	XXX ("Saint George Island, AK",  "STG"),
//	XXX ("Saint George, UT",  "SGU"),
//	XXX ("Saint Louis, MO",  "STL"),
//	XXX ("Saint Mary's, AK",  "KSM"),
//	XXX ("Saint Michael, AK",  "SMK"),
//	XXX ("Saint Paul Island, AK",  "SNP"),
//	XXX ("Salem, OR",  "SLE"),
//	XXX ("Salina, KS",  "SLN"),
//	XXX ("Salisbury-Ocean City, MD",  "SBY"),
//	XXX ("Salt Lake City, UT",  "SLC"),
//	XXX ("San Angelo, TX",  "SJT"),
//	XXX ("San Antonio, TX",  "SAT"),
//	XXX ("San Diego, CA",  "SAN"),
//	XXX ("San Francisco, CA",  "SFO"),
//	XXX ("San Jose, CA",  "SJC"),
//	XXX ("San Juan, Puerto Rico",  "SJU"),
//	XXX ("San Luis Obispo, CA",  "SBP"),
//	XXX ("Sand Point, AK",  "SDP"),
//	XXX ("Santa Ana, CA",  "SNA"),
//	XXX ("Santa Barbara, CA",  "SBA"),
//	XXX ("Santa Fe, NM",  "SAF"),
//	XXX ("Santa Maria, CA",  "SMX"),
//	XXX ("Santa Rosa, CA",  "STS"),
//	XXX ("Saranac Lake, NY",  "SLK"),
//	XXX ("Sarasota, FL",  "SRQ"),
//	XXX ("Sault Ste Marie, MI,",  "CIU"),
//	XXX ("Savannah, GA",  "SAV"),
//	XXX ("Savoonga, AK",  "SVA"),
//	XXX ("Scammon Bay, AK",  "SCM"),
//	XXX ("Scottsbluff, NE",  "BFF"),
//	XXX ("Scottsdale, AZ",  "SDL"),
//	XXX ("Scranton, PA",  "AVP"),
//	XXX ("Seattle, WA - Lake Union SPB",  "LKE"),
//	XXX ("Seattle, WA - Seattle/Tacoma International",  "SEA"),
//	XXX ("Selawik, AK",  "WLK"),
//	XXX ("Seward, AK",  "SWD"),
//	XXX ("Shageluk, AK",  "SHX"),
//	XXX ("Shaktoolik, AK",  "SKK"),
//	XXX ("Sheffield/Florence/Muscle Shoals, AL",  "MSL"),
//	XXX ("Sheldon Point, AK",  "SXP"),
//	XXX ("Sheridan, WY",  "SHR"),
//	XXX ("Shishmaref, AK",  "SHH"),
//	XXX ("Shreveport, LA",  "SHV"),
//	XXX ("Shungnak, AK",  "SHG"),
//	XXX ("Silver City, NM",  "SVC"),
//	XXX ("Sioux City, IA",  "SUX"),
//	XXX ("Sioux Falls, SD",  "FSD"),
//	XXX ("Sitka, AK",  "SIT"),
//	XXX ("Skagway, AK",  "SGY"),
//	XXX ("Sleetmore, AK",  "SLQ"),
//	XXX ("South Bend, IN",  "SBN"),
//	XXX ("South Naknek, AK",  "WSN"),
//	XXX ("Southern Pines, NC",  "SOP"),
//	XXX ("Spartanburg/Greenville, SC",  "GSP"),
//	XXX ("Spokane, WA",  "GEG"),
//	XXX ("Springfield, IL",  "SPI"),
//	XXX ("Springfield, MO",  "SGF"),
//	XXX ("St Petersburg/Clearwater, FL",  "PIE"),
//	XXX ("State College/University Park, PA",  "SCE"),
//	XXX ("Staunton, VA",  "SHD"),
//	XXX ("Steamboat Springs, CO",  "SBS"),
//	XXX ("Stebbins, AK",  "WBB"),
//	XXX ("Stevens Point/Wausau, WI",  "CWA"),
//	XXX ("Stevens Village, AK",  "SVS"),
//	XXX ("Stewart Field/Newburgh, NY",  "SWF"),
//	XXX ("Stockton, CA",  "SCK"),
//	XXX ("Stony River, AK",  "SRV"),
//	XXX ("Sun Valley, ID",  "SUN"),
//	XXX ("Syracuse, NY",  "SYR"),
//
//
//	XXX ("Takotna, AK",  "TCT"),
//	XXX ("Talkeetna, AK",  "TKA"),
//	XXX ("Tallahassee, FL",  "TLH"),
//	XXX ("Tampa, FL",  "TPA"),
//	XXX ("Tanana, AK",  "TAL"),
//	XXX ("Taos, NM",  "TSM"),
//	XXX ("Tatitlek, AK",  "TEK"),
//	XXX ("Teller Mission, AK",  "KTS"),
//	XXX ("Telluride, CO",  "TEX"),
//	XXX ("Tenakee Springs, AK",  "TKE"),
//	XXX ("Terre Haute, IN",  "HUF"),
//	XXX ("Tetlin, AK",  "TEH"),
//	XXX ("Texarkana, AR",  "TXK"),
//	XXX ("Thief River Falls, MN",  "TVF"),
//	XXX ("Thorne Bay, AK",  "KTB"),
//	XXX ("Tin City, AK",  "TNC"),
//	XXX ("Togiak Village, AK",  "TOG"),
//	XXX ("Tok, AK",  "TKJ"),
//	XXX ("Toksook Bay, AK",  "OOK"),
//	XXX ("Toledo, OH",  "TOL"),
//	XXX ("Topeka, KS",  "FOE"),
//	XXX ("Traverse City, MI",  "TVC"),
//	XXX ("Trenton/Mercer, NJ",  "TTN"),
//	XXX ("Tucson, AZ",  "TUS"),
//	XXX ("Tulsa, OK",  "TUL"),
//	XXX ("Tuluksak, AK",  "TLT"),
//	XXX ("Tuntutuliak, AK",  "WTL"),
//	XXX ("Tununak, AK",  "TNK"),
//	XXX ("Tupelo, MS",  "TUP"),
//	XXX ("Tuscaloosa, AL",  "TCL"),
//	XXX ("Twin Falls, ID",  "TWF"),
//	XXX ("Twin Hills, AK",  "TWA"),
//	XXX ("Tyler, TX",  "TYR"),
//
//
//	XXX ("Unalakleet, AK",  "UNK"),
//	XXX ("Urbana/Champaign, IL",  "CMI"),
//	XXX ("Utica, NY",  "UCA"),
//	XXX ("Utopia Creek, AK",  "UTO"),
//
//
//	XXX ("Vail, CO - Eagle County Airport",  "EGE"),
//	XXX ("Vail, CO - Van service",  "QBF"),
//	XXX ("Valdez, AK",  "VDZ"),
//	XXX ("Valdosta, GA",  "VLD"),
//	XXX ("Valparaiso, FL",  "VPS"),
//	XXX ("Venetie, AK",  "VEE"),
//	XXX ("Ventura/Oxnard, CA",  "OXR"),
//	XXX ("Vernal, UT",  "VEL"),
//	XXX ("Victoria, TX",  "VCT"),
//	XXX ("Visalia, CA",  "VIS"),
//
//
//	XXX ("Waco, TX",  "ACT"),
//	XXX ("Wainwright, AK",  "AIN"),
//	XXX ("Wales, AK",  "WAA"),
//	XXX ("Walla Walla, WA",  "ALW"),
//	XXX ("Washington DC - All airports",  "WAS"),
//	XXX ("Washington DC - Dulles",  "IAD"),
//	XXX ("Washington DC - National",  "DCA"),
//	XXX ("Waterfall, AK",  "KWF"),
//	XXX ("Waterloo, IA",  "ALO"),
//	XXX ("Watertown, NY",  "ART"),
//	XXX ("Watertown, SD",  "ATY"),
//	XXX ("Wausau/Stevens Point, WI",  "CWA"),
//	XXX ("Wenatchee, WA",  "EAT"),
//	XXX ("West Palm Beach, FL",  "PBI"),
//	XXX ("West Yellowstone, MT",  "WYS"),
//	XXX ("Westchester County, NY",  "HPN"),
//	XXX ("Westerly, RI",  "WST"),
//	XXX ("Westsound, WA",  "WSX"),
//	XXX ("Whale Pass, AK",  "WWP"),
//	XXX ("White Mountain, AK",  "WMO"),
//	XXX ("White River, VT",  "LEB"),
//	XXX ("Wichita Falls, TX",  "SPS"),
//	XXX ("Wichita, KS",  "ICT"),
//	XXX ("Wilkes Barre, PA",  "AVP"),
//	XXX ("Williamsburg, VA",  "PHF"),
//	XXX ("Williamsport, PA",  "IPT"),
//	XXX ("Williston, ND",  "ISN"),
//	XXX ("Wilmington, NC",  "ILM"),
//	XXX ("Windsor Locks, CT",  "BDL"),
//	XXX ("Worcester, MA",  "ORH"),
//	XXX ("Worland, WY",  "WRL"),
//	XXX ("Wrangell, AK",  "WRG"),
//
//
//	XXX ("Yakima, WA",  "YKM"),
//	XXX ("Yakutat, AK",  "YAK"),
//	XXX ("Yellowstone/Cody, WY",  "COD"),
//	XXX ("Youngstown, OH",  "YNG"),
//	XXX ("Yuma, AZ",  "YUM"),


	;
		
	private String mAirportName;
	private String mAirportCode;
	
	private Airport(String airportName, String airportCode) {
		mAirportName = airportName;
		mAirportCode = airportCode;
	}
	
	public String getCode() {
		return mAirportCode;
	}
	
	public String toString() {
		return mAirportName;
	}
}
